ADDRESS_STREET: 123 Main St
API_URL: https://jsonplaceholder.typicode.com/posts
CLIENT_ID: sample_client_id
CLIENT_SECRET: sample_client_secret
EMPLOYMENT_START_DATE: "2020-01-15"
HOBBIES: reading
RESPONSE_DATE: Tue, 10 Sep 2024 10:57:54 GMT
